In [36]:
import numpy as np
Even_array = np.arange(30,71,2)
print(Even_array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [64]:
from numpy import random
x = random.normal(100,size=(15))
print(x)

[101.25185615  99.63101304 101.61634916  99.77670584  99.53538222
 101.41245736  98.84598713  99.46535544  99.18238875 100.74089155
  98.66298843  98.59087075  99.74891676 100.05708484 100.2636296 ]


In [86]:
import numpy as np
matrix1 = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

matrix2 = np.array([[10,11,12],
                    [13,14,15],
                    [16,17,18]])

crossproduct = np.cross(matrix1,matrix2)
print("The crossproduct is : \n")
print(crossproduct)


The crossproduct is : 

[[-9 18 -9]
 [-9 18 -9]
 [-9 18 -9]]


In [94]:
import numpy as np
arr = np.array([[1,2],
                [3,4]])

determinant = np.linalg.det(arr)
print("determinant = ",det)

determinant =  -2.0000000000000004


In [99]:
from numpy import random
arr = np.random.rand(3,3,3)
print(arr)

[[[0.43482719 0.62429003 0.03802184]
  [0.31402971 0.42506776 0.38390541]
  [0.5269217  0.68602521 0.25155844]]

 [[0.80505783 0.98409437 0.333215  ]
  [0.26372341 0.98580797 0.29317032]
  [0.59165624 0.65502232 0.45958057]]

 [[0.52782928 0.7405185  0.23814488]
  [0.51243259 0.12679333 0.91549676]
  [0.84587916 0.7656344  0.34315077]]]


In [106]:
import numpy as np
arr = np.random.rand(5,5)
print(arr)

[[0.96162583 0.6311574  0.06760868 0.74739983 0.50676086]
 [0.41412925 0.8465395  0.08941623 0.56938025 0.28667975]
 [0.87800519 0.48651839 0.016431   0.71864023 0.10641088]
 [0.19251503 0.46395982 0.48807333 0.44585517 0.78362634]
 [0.38255571 0.80073027 0.21055881 0.42549426 0.99034806]]


In [116]:
import numpy as np
arr = np.random.rand(5,5)
minimum = np.min(arr)
maximum = np.max(arr)
print(arr)
print(minimum,maximum)

[[0.43403122 0.89381374 0.91168719 0.65882389 0.91517151]
 [0.429688   0.01794189 0.93947613 0.36517031 0.41338389]
 [0.2046954  0.67556737 0.79439562 0.51731339 0.85068076]
 [0.52815695 0.50640738 0.81184342 0.22879097 0.5735817 ]
 [0.73386575 0.56488218 0.468684   0.98568972 0.27711162]]
0.01794189383802336 0.9856897210522172


In [124]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

mean = np.mean(arr , axis = 1)
std = np.std(arr , axis = 1)
varience = np.var(arr , axis = 1)

print(mean,std,varience)


[2. 5. 8.] [0.81649658 0.81649658 0.81649658] [0.66666667 0.66666667 0.66666667]
